# Unique name for this workflow
name: Salesforce DX (staging)

# Definition when the workflow should run
on:
    pull_request:
        branches:
            - staging
        paths:
            - 'force-app/**'

# Jobs to be executed
jobs:   
    scratch-org-test:
        runs-on: ubuntu-latest
        steps:
            # Install Salesforce CLI
            - name: Install Salesforce CLI
              run: |
                    npm install sfdx-cli
                    node_modules/sfdx-cli/bin/run --version
                    node_modules/sfdx-cli/bin/run plugins --core
            # Checkout the code in the pull request
            
            - name: 'Checkout source code'
              uses: actions/checkout@v2

            # Store secret for dev hub
            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
              shell: bash
              run: 'echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'

            # Authenticate dev hub
            - name: 'Authenticate Dev Hub'
              run: 'sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d'
            
            # Authenticate staging sandbox
            - name: 'Authenticate staging sandbox'
              run: 'sfdx force:auth:sfdxurl:store -f ./STAGING_SFDX_URL.txt -a staging -s'
            
            # Lint Aura components
            - name: 'Lint Aura components'
              run: 'sfdx force:lightning:lint force-app/main/default/aura --exit'

            # Validate source to staging sandbox
            - name: 'Validate source to staging sandbox'
              run: 'sfdx force:source:deploy --checkonly --testlevel RunLocalTests -u staging'
